apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nfs-volume
          mountPath: /tmp
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: mypvc-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-nfs
spec:
  resources:
    requests:
      storage: 500Mi
  storageClassName: my-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-nfs
provisioner: microk8s.io/hostpath
